name: iotelkiosk
version: 1.0.0+1
publish_to: none
description: A Kiosk application written in Flutter and Dart, this will be use in a Hotel for easy transaction, this kiosk is connected via PMS, Property Management System with the integration on hardware like Printer, Card Issuance, etc.
environment: 
  # sdk: '>=2.19.0 <3.0.0'
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  #local library
  system_idle: 
    path: ./library/system_idle

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter

  #WINDOW UI
  window_manager: ^0.3.4
  sizer: ^2.0.15
  one_clock: ^1.0.8
  timezone: ^0.9.1
  flutter_svg: ^2.0.0+1
  vector_graphics_compiler: ^1.0.1
  flutter_carousel_widget: ^2.0.2
  virtual_keyboard_multi_language: ^1.0.3
  flutter_form_builder: ^9.1.1
  flutter_datetime_picker: ^1.5.1
  marquee: ^2.2.3
  flutter_animate: ^4.1.1+1
  camera_windows: ^0.2.1+8
  translator: ^0.1.7
  ffi: ^2.0.2
  win32: ^5.0.3

  # MEDIA AND AUDIO
  media_kit: ^1.1.8+2
  media_kit_video: ^1.2.1                        # For video rendering.
  media_kit_libs_video: ^1.0.3

  # WEB COMMUNICATION 
  signalr_core: ^1.1.1
  
  # proste_indexed_stack: ^0.2.4
  #local_session_timeout: ^2.2.0  //for local activity checkier
  # expandable_page_view: ^1.0.17

  #FORMATTING and DATE
  intl: ^0.18.1

  #HTTP COMMUNICATION
  http: ^0.13.5
  hasura_connect: ^4.0.0+4

  #STORAGE
  get_storage: ^2.1.1

  #SERIAL COMMUNICATION 
  # serial_port_win32: ^0.7.0
  flutter_libserialport: ^0.3.0

  #ACCESSIBILITY
  hex: ^0.2.0
  # accessibility_tools: ^1.0.0

  
  #WIN32.PUB
  # windows_graphics: ^0.0.4+1
  # windows_devices: ^0.0.2+2

  # ANIMATIONS AND PLAYER
  dotlottie_loader: ^0.0.3
  lottie: ^2.6.0

  # LOGGING
  logger: ^2.0.2+1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter:
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/PRODUCT-SANS-REGULAR.ttf
        - asset: fonts/PRODUCT-SANS-BOLD-ITALIC.ttf
          # style: italic
  assets:
    - assets/background/
    - assets/icons/
    - assets/locales/
    - assets/svg/
    - assets/png/
    - assets/menus/
    - assets/lottie/
    - assets/logo/
    - assets/hardware/
  uses-material-design: true

